VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IPcreOptions"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Function Compile() As IPcreOptionsCompile
End Function

Public Function General() As IPcreOptionsGeneral
End Function

Public Function Match() As IPcreOptionsMatch
End Function

Public Function Replace() As IPcreOptionsReplace
End Function

